config/routes.rb
Pairconnect::Application.routes.draw do
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  root to: "users#index"

  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end
  resources :password_resets
  resources :friends, controller: 'friendships', except: [:show, :edit] do
    get "requests", on: :collection
    get "invites", on: :collection
  end

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  include Amistad::FriendModel
  include Gravtastic
  gravtastic
  friendly_id :username, use: :slugged
  authenticates_with_sorcery!

  validates :password, length: {minimum: 8}, unless: :guest?, on: :create
  validates :password, confirmation: true, unless: :guest?, on: :create
  validates :password_confirmation, presence: true, unless: :guest?, on: :create
  validates :email, uniqueness: true, unless: :guest?
  validates :email, presence: true, unless: :guest?
  validates :username, presence: true, unless: :guest?
  validates :username, uniqueness: true, unless: :guest?

  has_one :profile, :dependent => :destroy
  has_many :projects, :dependent => :destroy
  accepts_nested_attributes_for :projects, :allow_destroy => true
  accepts_nested_attributes_for :profile, :allow_destroy => true

  def self.new_guest
    new { |u| u.guest = true }
  end

  def name
    guest ? "Guest" : username
  end

  def self.get_current_users
    config = sorcery_config
    where("#{config.last_activity_at_attribute_name} IS NOT NULL") \
    .where("#{config.last_logout_at_attribute_name} IS NULL
      OR #{config.last_activity_at_attribute_name} > #{config.last_logout_at_attribute_name}") \
    .where("#{config.last_activity_at_attribute_name} > ? ", config.activity_timeout.seconds.ago.utc.to_s(:db))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create, :activate]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @projects = @user.projects.limit(5)
    @online = User.get_current_users.include?(@user)
  end

  # GET /users/new
  def new
    if session[:user_id]
      user = User.friendly.find(session[:user_id])
      if !user.guest?
        redirect_back_or_to(:users, notice: "You're Already Logged In")
      elsif user.guest?
        @user = User.new
        @user.build_profile if @user.profile.nil?
      end
    else
      @user = User.new
      @user.build_profile if @user.profile.nil?
    end
  end

  # GET /users/1/edit
  def edit
    if !verify_current_user
      redirect_to root_url, notice: "You don't have permission to do this."
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = params[:user] ? User.new(user_params) : User.new_guest
    @user.build_profile if @user.profile.nil?

    if @user.save
      if @user.guest?
        session[:user_id] = @user.id
        redirect_to root_url, notice: "Guest Account Successfully Created."
      else
        redirect_to root_url, notice: "Check Your Email to Activate Your Account."
      end
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if verify_current_user
      if @user.update(user_params)
        flash[:notice] = "Successfully Updated!"
        render :edit
      else
        render action: 'edit'
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if verify_current_user
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, notice: "You aren't permitted to do this." }
      end
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(login_path, notice: "Used was successfully activated.")
    else
      not_authenticated
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :profile_attributes => [:id, :name, :bio, :twitter_handle, :github_username, :website, :languages, :skill_level, :best_time, :goal, :_destroy], :projects_attributes => [:id, :name, :url, :description, :language, :source_code_url, :goals, :requirements, :_destroy])
  end

  def verify_current_user
    @user.id == session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def skill_level(level)
    skill_level_str = ""
    if level == "newbie"
      skill_level_str += "Total Newbie"
    elsif level == "novice"
      skill_level_str += "Novice"
    elsif level == "advanced_beginner"
      skill_level_str += "Advanced Beginner"
    elsif level == "intermediate"
      skill_level_str += "Intermediate"
    elsif level == "advanced"
      skill_level_str += "advanced"
    end
    return skill_level_str
  end
end

app/views/users/_form.html.erb
<%= nested_form_for(@user, html: {multipart: true, class: "pure-form pure-form-stacked #{class_name}"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= yield f %>
    <%= f.submit 'Submit', class: "pure-button button-primary" %>
<% end %>

app/views/users/edit.html.erb
<section>
<div class="pure-g">
  <div class="pure-u-1-3">
    <ul class="edit-profile-menu">
      <li class="edit-profile-link active">Edit Profile</li>
      <li class="edit-social-info-link">Edit Social Information</li>
      <li class="edit-pairing-info-link">Edit Pairing Information</li>
    </ul>
  </div>
  <div class="pure-u-2-3">
    <%= render :layout => 'form', locals: {class_name: "edit-form"} do |f| %>
    <div class="edit-profile-form">
      <h3 class="text-center">Edit Profile</h3>
        <%= f.email_field :email, placeholder: "Your Email" %>
        <%= f.text_field :username, placeholder: "Your Username" %>
        <%= f.fields_for :profile do |pf| %>
          <%= pf.text_field :name, placeholder: "Your Name" %>
          <%= pf.text_area :bio, placeholder: "A Little Bit About You" %>
        <% end %>
        </div>

        <div class="social-form" style="display:none;">
          <h3 class="text-center">Edit Social Information</h3>
          <%= f.fields_for :profile do |pf| %>
            <%= pf.text_field :twitter_handle, placeholder: "Twitter Handle"%>
            <%= pf.text_field :github_username, placeholder: "GitHub Username" %>
            <%= pf.url_field :website, placeholder: "Your Website" %>
          <% end %>
        </div>

        <div class="pairing-form" style="display:none;">
          <h3 class="text-center">Edit Pairing Information</h3>
          <%= f.fields_for :profile do |pf| %>
            <%= pf.text_field :languages, placeholder: "Languages you have experience with, or want to use during pairing." %>
            <div class="form-group">
            <%= pf.select(:skill_level, options_for_select([['Total Newbie', 'newbie'], ['Novice', 'novice'], ['Advanced Beginner', 'advanced_beginner'], ['Intermediate', 'intermediate'], ['Advanced', 'advanced']]), {prompt: "Select your Skill Level"}, {id: "ms", selected: @user.profile.skill_level}) %>
            </div>
            <div class="form-group">
              <%= pf.text_field :best_time, placeholder: "Best Times for Pairing?" %>
            </div>
            <div class="form-group">
              <%= pf.text_area :goal, placeholder: "What do you hope to achieve during a pairing session?" %>
            </div>
          <% end %>

        <h3 class="text-center">Your Projects</h3>
        <%= f.fields_for :projects do |pjf| %>
          <%= pjf.text_field :name, placeholder: "Name of Your Project" %>
          <%= pjf.text_area :description, placeholder: "Describe the Project" %>
          <%= pjf.text_field :url, placeholder: "URL of Project (if available)" %>
          <%= pjf.text_field :language, placeholder: "Language(s) the Project Uses" %>
          <%= pjf.text_field :source_code_url, placeholder: "URL of the Source Code" %>
          <%= pjf.text_area :requirements, placeholder: "Requirements for Starting on this Project (dependencies, libraries, etc)" %>
          <%= pjf.link_to_remove "Remove this Project", class: "button-error pure-button" %>
        <% end %>
        <% if @user.projects.blank? %>
          <p class="no-project-text">You haven't added a project yet.</p>
        <% end %>
        <%= f.link_to_add "Add a Project", :projects, class: "pure-button button-primary add-project" %>
        <br>
      </div>

      <div class="notification-form" style="display:none;">
        <h3 class="text-center">Edit Notification Settings</h3>
        notifications will go here
      </div>

      <div class="cancel-account-form" style="display:none;">
        <h3 class="text-center danger">Cancel Account</h3>
        form will go here
      </div>
    <% end %>
  </div>
</div>
<script>
  $(function() {
  $('#ms-1').change(function() {
    console.log($(this).val());
  }).multipleSelect({
  placeholder: "Please Select Your Best Times for Pairing",
  width: '80%'
  })
  });
  $(function() {
  $('#ms-2').change(function() {
    console.log($(this).val());
  }).multipleSelect({
  placeholder: "What do you want to achieve during a pair session?",
  width: '80%'
  })
  });

</script>
</section>

app/views/users/index.html.erb
<section class="users">
<div class="pure-g">
  <div class="pure-u-1-1">
    <div class="explanation"><h1>PairConnect is connecting you with your next pair.</h1>
      <script type="text/javascript">
        var rumbleBannerBackgroundColor, rumbleBannerTextColor, rumbleBannerLinkColor, rumbleBannerPlacement;
        rumbleBannerBackgroundColor = "#161616";
        rumbleBannerTextColor = "#b0b0b0";
        rumbleBannerLinkColor = "#ffffff";
        rumbleBannerPlacement = "bottom"; // Optionally replace with "bottom".
        </script>
                <script src="https://d4nnn7wspfa3h.cloudfront.net/banner-2014.js" type="text/javascript"></script>
    <% if !current_user %>
      <%= link_to "Create Your Account Today", new_user_path, class: "pure-button" %>
    <% end %>
  </div>
  </div>
</div>

<% if @users %>
  <div class="pure-g">
    <% @users.each do |user| %>
    <div class="pure-u-1-1">
        <% unless user.guest? %>
            <a href="/users/<%= user.slug %>">
            <div class="user-item">
              <div class="pure-u-1-3">
                <span class="avatar"><%= image_tag user.gravatar_url(size: 75, default: "identicon") %></span>
                <span class="username"><i class="fa fa-user"></i> <%= user.username %></span>
              </div>
              <div class="pure-u-1-3">
                <% if !user.profile.nil? %>
                  <% if !user.profile.skill_level.nil? %>
                    <p><strong>Skill Level</strong>: <%= skill_level(user.profile.skill_level) %></p>
                  <% end %>
                  <p><strong>Number of Projects</strong>: <%= user.projects.count %></p>
                  <%if !user.profile.bio.nil? %>
                    <p><strong>Bio</strong>: <%= user.profile.bio %></p>
                  <% end %>
                <% end %>
                </div>
              </div>
            </a>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>
</section>

app/views/users/new.html.erb
<section class="register"><h3>Create a PairConnect Account</h3>

<%= render :layout => "form", locals: {class_name: "sign-up-form"} do |f| %>
  <div class="pure-g">
    <div class="pure-u-1 pure-u-md-3-3">
      <%= f.email_field :email, placeholder: "E-Mail Address." %>
    </div>

    <div class="pure-u-1 pure-u-md-3-3">
      <%= f.text_field :username, placeholder: "Username" %>
    </div>

    <div class="pure-u-1 pure-u-md-3-3">
      <%= f.password_field :password, placeholder: "Password" %>
    </div>

    <div class="pure-u-1 pure-u-md-3-3">
      <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
    </div>
<% end %>
</section>

app/views/users/show.html.erb
<section class="user-profile">
<div class="user-header">
  <div class="user-information">
    <% if current_user == @user %>
    <span class="edit-profile"><%= link_to "<i class='fa fa-cog'></i> Edit Profile".html_safe, edit_user_path(@user), class:"pure-button pure-button-primary edit-profile-link" %></span>
  <% end %>
    <span class="avatar"><%= image_tag @user.gravatar_url(size: 150, default: "identicon") %></span>
    <span class="name"><%= @user.profile.try(:name) %></span>
    <span class="username"><%= @user.username %></span>
    <span class="email"><i class="fa fa-envelope"></i> <a href="mailto:<%= @user.email %>"><%= @user.email %></a></span>
    <span class="social">
      <% if !@user.profile.nil? %>
        <% if !@user.profile.twitter_handle.nil? %>
          <a href="http://twitter.com/<%= @user.profile.twitter_handle %>"><i class="fa fa-twitter"></i></a>
        <% end %>
        <% if !@user.profile.github_username.nil? %>
          <a href="http://github.com/<%= @user.profile.github_username %>"><i class="fa fa-github"></i></a>
        <% end %>
        <% if !@user.profile.website.nil? %>
          <a href="<%= @user.profile.website %>"><i class="fa fa-link"></i></a>
        <% end %>
      <% end %>
    </span>

  </div>
  <div class="user-bar">
    <% if @online %>
      <span class="online-now"><strong><i class="fa fa-asterisk"></i> User is Online Now</strong></span>
    <% end %>
    <% unless @user == current_user %>
    <% end %>
  </div>
</div>

<div class="user-profile">
  <span class="bio-section"><h3 class="bio-header">About <%= @user.username %></h3></span>
  <div class="aligncenter"></div>
  <div class="basic-info">
    <% if !@user.profile.nil? %>
      <% if current_user ==  @user && @user.profile.bio.blank? %>
        <p>Add your bio by <%= link_to "editing your profile", edit_user_path(@user) %></p>
      <% end %>
      <%= @user.profile.bio %><br/>
    </div>
    <% if @user.profile.languages.nil? && @user.profile.skill_level.nil? && @user.profile.best_time.nil? && @user.profile.goal.nil? %>
      <% if current_user == @user %>
        <span class="bio-section"><h3 class="bio-header">Pairing Information</h3></span>
        <div class="aligncenter"></div>
        <div class="pairing-info">
          <p>Add your pairing information by <%= link_to "editing your profile", edit_user_path(@user) %></p>
        </div>
      <% end %>
    <% else %>
    <span class="bio-section"><h3 class="bio-header">Pairing Information</h3></span>
    <div class="aligncenter"></div>
    <div class="pairing-info">
      <ul>
        <li><strong>Languages</strong>: <%= @user.profile.languages %></li>
        <li><strong>Skill Level</strong>: <%= skill_level(@user.profile.skill_level) %></li>
        <li><strong>Best Time</strong>: <%= @user.profile.best_time %></li>
        <li><strong>Goal of Pairing Session</strong>: <%= @user.profile.goal %></li>
      </ul>
    </div>
  <% end %>
  <% end %>
  <% if @user.projects.blank? %>
    <% if current_user == @user %>
      <span class="bio-section"><h3 class="bio-header">Project Information</h3></span>
      <div class="aligncenter"></div>
      <div class="project-info">
        <p>Are you working on a project? Add it by <%= link_to "editing your profile", edit_user_path(@user) %></p>
      </div>
    <% end %>
  <% else %>
    <span class="bio-section"><h3 class="bio-header">Project Information</h3></span>
    <div class="aligncenter"></div>
    <div class="project-info">
      <% if !@user.projects.blank? %>
        <ul>
          <% @user.projects.each do |pr| %>
            <h4 class="project-name"><%= pr.name %></h4>
            <li><strong>URL</strong>: <%= pr.url %></li>
            <li><strong>Description</strong>: <%= pr.description %></li>
            <li><strong>Language(s)</strong>: <%= pr.language %></li>
            <li><strong>Source Code</strong>: <%= pr.source_code_url %></li>
            <li><strong>Goals</strong>: <%= pr.goals %></li>
            <li><strong>Requirements</strong>: <%= pr.requirements %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    </p>
  </div>
<% end %>
</section>