config/routes.rb
Pairconnect::Application.routes.draw do
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  root to: "users#index"

  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end
  resources :password_resets
  resources :friends, controller: 'friendships', except: [:show, :edit] do
    get "requests", on: :collection
    get "invites", on: :collection
  end

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
    @friends = current_user.friends
  end

  def new
    @friends = User.all conditions: ["id != ?", current_user.id]
  end

  def create
    invitee = User.find_by_slug(params[:user_id])
    if current_user.invite invitee
      redirect_to new_friend_path, notice: "Successfully Invited #{invitee.username}"
    else
      redirect_to new_friend_path, notice: "Sorry! You can't invite that user."
    end
  end

  def update
    inviter = User.find_by_slug(params[:id])
    if current_user.approve inviter
      redirect_to new_friend_path, notice: "Successfully confirmed #{inviter.username}"
    else
      redirect_to new_friend_path, notice: "Sorry! Could not confirm #{inviter.username}"
    end
  end

  def requests
    @pending_requests = current_user.pending_invited_by
  end

  def invites
    @pending_invites = current_user.pending_invites
  end

  def destroy
    user = User.find_by_slug(params[:id])
    if current_user.remove_friendship user
      redirect_to friends_path, notice: "Succesfully removed friend!"
    else
      redirect_to friends_path, notice: "Sorry, couldn't remove friend!"
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<section class="friends-index">
<% if !@friends.blank? %>
  <% @friends.each do |usr| %>
    <a href="/users/<%= usr.slug %>">
      <div class="user-item">
        <div class="pure-u-3-3">
          <span class="avatar"><%= image_tag user.gravatar_url(size: 75, default: "identicon") %></span>
          <span class="username"><i class="fa fa-user"></i><%= user.username %></span>
        </div>
    <%= link_to "Go to #{usr.username}'s page", user_path(usr) %>
  <% end %>
<% else %>
  <p>You have no friends :( </p>
<% end %>
</section>

app/views/friendships/new.html.erb
<section style="padding-top:10em;">
<ul>
  <% @friends.each do |user| %>
    <% if !user.guest %>
      <li>
      <% if current_user.friend_with? user %>
        <%= user.username %>
        <p>You are already friends!</p>
      <% elsif current_user.invited? user %>
        <%= user.username %>
        <p>Pending request...</p>
      <% elsif user.invited? current_user %>
        <%= user.username %>
        <%= link_to "Confirm friend?", friend_path(user), method: "put" %>
      <% else %>
        <%= user.username %>
        <%= link_to "Add friend?", friends_path(:user_id => user), method: "post" %>
      <% end %>
      </li>
    <% end %>
  <% end %>
</ul>
</section>