config/routes.rb
Pairconnect::Application.routes.draw do
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  root to: "users#index"

  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end
  resources :password_resets
  resources :friends, controller: 'friendships', except: [:show, :edit] do
    get "requests", on: :collection
    get "invites", on: :collection
  end

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to(:users, notice: "Login successful")
    else
      flash.now[:alert] = "Login failed"
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: "Logged out.")
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<section class='login'>
<%= bootstrap_form_tag url: user_sessions_path, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10", :method => :post do |f| %>
    <%= f.text_field :email %>
    <%= f.password_field :password %>
    <%= f.form_group do %>
    <%= f.check_box :remember, label: "Remember Me"  %>
    <%= f.submit "Log In", class: "pure-button button-primary login-button" %>
    <% end %>
<% end %>
</section>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<section class="login">
<h1>Log In</h1>
<%= render 'form' %>
<%= link_to "Forgot Password?", new_password_reset_path %>
</section>