config/routes.rb
Pairconnect::Application.routes.draw do
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  root to: "users#index"

  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end
  resources :password_resets
  resources :friends, controller: 'friendships', except: [:show, :edit] do
    get "requests", on: :collection
    get "invites", on: :collection
  end

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairconnect</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  asset_path("application.css"), media: "all" %>
  <%= javascript_include_tag asset_path("application.js") %>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/buttons-min.css">
  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="cwV9YL3gMwoFOmIBpHafpd2dE6GOoWpLfT4ntdwdmxI" />

</head>
<body>

    <div class='container'>
    <header id="header" class="header header-large">
    <div class="header-perspective">
      <div class="header-front">
        <h1><span>Pair Connect</span></h1>
        <nav>
        <%= link_to "Home", root_path %>
        <% if current_user %>
          <% if current_user.guest? %>
            <%= link_to "Become a Member", new_user_path %>
          <% else %>
            <%= link_to "My Profile", user_path(current_user.id) %>
            <%= link_to "Log Out", :logout, method: :post %>
          <% end %>
        <% else %>
          <%= link_to "Register", new_user_path %> <%= link_to "Log In", :login  %> <%= link_to "Try as a Guest", users_path, method: :post, class: "try-as-guest"%>
        <% end %>
        </nav>
      </div>
      <div>
    </header>

    <% if flash[:notice] %>
      <p id="flash_notice"><%= flash[:notice] %></p>
    <% end %>

    <%= yield %>

  <%= javascript_include_tag asset_path("waypoints.js"), "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>pair connect | connecting you with your next pair.</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  asset_path("static.css"), media: "all" %>
  <%= javascript_include_tag asset_path("static.js") %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section id="navbar">
  <div class="container">
    <a href="/"><h1><span>Pair Connect</span></h1>
      <ul class="navigation-links">
        <%= link_to "Home", root_path %>
        <% if current_user %>
          <% if current_user.guest? %>
            <li><%= link_to "Become a Member", new_user_path %></li>
          <% else %>
            <li><%= link_to "My Profile", user_path(current_user.id) %></li>
            <li><%= link_to "Log Out", :logout, method: :post %></li>
          <% end %>
        <% else %>
          <li><%= link_to "Register", new_user_path %> <%= link_to "Log In", :login  %> <%= link_to "Try as a Guest", users_path, method: :post, class: "try-as-guest"%></li>
        <% end %>
      </ul>
    </div>
    </section>

    <header>
    <div class="container">
      <h2><span class="highlight">PairConnect </span> is connecting you with your next pair.</h2>
    </div>
    </header>

    <section class="container">
    <%= yield %>
    </section>

    <footer class="row">
    <div class="column one-third">
      <p>Pair Connect was made as part of <%= link_to "Rails Rumble "
</body>